"""Planning, search-limit, and field-filter declarations."""

from __future__ import annotations

from .settings_spec_types import SettingSpec

PLANNING_SETTINGS = (
    SettingSpec(
        "limit",
        ("limits", "limit"),
        200,
        "--limit",
        int,
        section="planning",
        fallback=0,
        help="要获取/测试的字段数量；0 表示所有字段",
    ),
    SettingSpec(
        "offset",
        ("limits", "offset"),
        0,
        "--offset",
        int,
        section="planning",
        fallback=0,
        help="字段偏移量",
    ),
    SettingSpec(
        "page_size",
        ("limits", "page_size"),
        50,
        "--page-size",
        int,
        section="planning",
        fallback=1,
        dataset_profile=True,
        help="分页大小",
    ),
    SettingSpec(
        "sleep_between_fields",
        ("limits", "sleep_between_fields"),
        5.0,
        "--sleep-between-fields",
        float,
        section="planning",
        fallback=0.0,
        dataset_profile=True,
        help="字段间的休眠时间（增大以降低 API 限流）",
    ),
    SettingSpec(
        "max_templates_per_field",
        ("limits", "max_templates_per_field"),
        6,
        "--max-templates-per-field",
        int,
        section="planning",
        fallback=0,
        dataset_profile=True,
        help="每个字段测试的最大模板数；0 表示所有内置模板",
    ),
    SettingSpec(
        "max_templates_per_family",
        ("limits", "max_templates_per_family"),
        1,
        "--max-templates-per-family",
        int,
        section="planning",
        fallback=0,
        help="每个表达式家族保留的最大候选数；0 表示不限制",
    ),
    SettingSpec(
        "max_new_simulations",
        ("limits", "max_new_simulations"),
        0,
        "--max-new-simulations",
        int,
        section="planning",
        fallback=0,
        help="本次启动最多调度的 simulation 数量；0 表示不限制",
    ),
    SettingSpec(
        "field_template_batch_size",
        ("limits", "field_template_batch_size"),
        2,
        "--field-template-batch-size",
        int,
        section="planning",
        fallback=1,
        dataset_profile=True,
        help="每轮每个字段最多发出的模板/setting 组合数；最小为 1，默认 2",
    ),
    SettingSpec(
        "similarity_penalty",
        ("limits", "similarity_penalty"),
        42,
        "--similarity-penalty",
        int,
        section="planning",
        fallback=0,
        cli_aliases=("--legacy-similarity-penalty",),
        yaml_aliases=(("limits", "legacy_similarity_penalty"),),
        help="应用于 raw/group-rank/simple-ratio 等模板的优先级惩罚",
    ),
    SettingSpec(
        "top_fields_by_feedback",
        ("filters", "top_fields_by_feedback"),
        0,
        "--top-fields-by-feedback",
        int,
        section="planning",
        fallback=0,
        help="如果大于 0，仅测试按反馈排序的前 N 个字段",
    ),
)
