"""Concurrency, retry, and polling setting declarations."""

from __future__ import annotations

from .settings_spec_types import SettingSpec

EXECUTION_SETTINGS = (
    SettingSpec(
        "max_concurrent_simulations",
        ("concurrency", "max_concurrent_simulations"),
        1,
        "--max-concurrent-simulations",
        int,
        section="execution",
        fallback=1,
        dataset_profile=True,
        help="并发模拟的最大数量（降低以避免 API 限流）",
    ),
    SettingSpec(
        "max_concurrent_creates",
        ("concurrency", "max_concurrent_creates"),
        1,
        "--max-concurrent-creates",
        int,
        section="execution",
        fallback=1,
        dataset_profile=True,
        help="并发模拟创建请求的最大数量",
    ),
    SettingSpec(
        "min_request_interval",
        ("retries", "min_request_interval"),
        2.5,
        "--min-request-interval",
        float,
        section="execution",
        fallback=0.0,
        dataset_profile=True,
        help="请求间的最小间隔，用于降低速率限制（增大以应对 API 429）",
    ),
    SettingSpec(
        "rate_limit_max_retries",
        ("retries", "rate_limit_max_retries"),
        5,
        "--rate-limit-max-retries",
        int,
        section="execution",
        fallback=0,
        help="速率限制时的最大重试次数",
    ),
    SettingSpec(
        "login_retries",
        ("retries", "login_retries"),
        3,
        "--login-retries",
        int,
        section="execution",
        fallback=0,
        help="登录重试次数",
    ),
    SettingSpec(
        "simulation_create_retries",
        ("retries", "simulation_create_retries"),
        3,
        "--simulation-create-retries",
        int,
        section="execution",
        fallback=0,
        help="模拟创建重试次数",
    ),
    SettingSpec(
        "simulation_poll_retries",
        ("retries", "simulation_poll_retries"),
        3,
        "--simulation-poll-retries",
        int,
        section="execution",
        fallback=0,
        help="模拟轮询重试次数",
    ),
    SettingSpec(
        "simulation_max_polls",
        ("retries", "simulation_max_polls"),
        240,
        "--simulation-max-polls",
        int,
        section="execution",
        fallback=1,
        help="单个模拟的最大轮询次数",
    ),
    SettingSpec(
        "simulation_max_wait_seconds",
        ("retries", "simulation_max_wait_seconds"),
        1800.0,
        "--simulation-max-wait-seconds",
        float,
        section="execution",
        fallback=1.0,
        dataset_profile=True,
        help="单个模拟的最大等待时间（秒）",
    ),
    SettingSpec(
        "simulation_max_pending_cycles",
        ("retries", "simulation_max_pending_cycles"),
        120,
        "--simulation-max-pending-cycles",
        int,
        section="execution",
        fallback=1,
        help="最大等待周期数",
    ),
    SettingSpec(
        "simulation_max_queue_seconds",
        ("retries", "simulation_max_queue_seconds"),
        600.0,
        "--simulation-max-queue-seconds",
        float,
        section="execution",
        fallback=1.0,
        dataset_profile=True,
        help="最大队列等待时间（秒）",
    ),
    SettingSpec(
        "queue_busy_cooldown_seconds",
        ("retries", "queue_busy_cooldown_seconds"),
        300.0,
        "--queue-busy-cooldown-seconds",
        float,
        section="execution",
        fallback=0.0,
        dataset_profile=True,
        help="队列拥塞后的冷却时间（秒，增大以避免重复触发限流）",
    ),
    SettingSpec(
        "queue_busy_retry_limit",
        ("retries", "queue_busy_retry_limit"),
        2,
        "--queue-busy-retry-limit",
        int,
        section="execution",
        fallback=0,
        help="单候选队列拥塞重试上限；0 表示不限制",
    ),
    SettingSpec(
        "check_submission_retries",
        ("retries", "check_submission_retries"),
        3,
        "--check-submission-retries",
        int,
        section="execution",
        fallback=0,
        help="Check Submission 请求或空响应的重试次数",
    ),
)
